#!/usr/bin/env bash
# Transfer a file to your server

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
	exit 0
fi

args=("$@")

scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ${args[0]} ${args[2]}@${args[1]}:~${args[3]}
