#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
#

# install nginx web server
sudo apt-get -y update && \
sudo apt-get -y install nginx

# Starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Overriding the default page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Restarting nginx
sudo service nginx restart
