#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
# Craete a redirect location context

# install nginx web server
sudo apt-get -y update && \
sudo apt-get -y install nginx

# Starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Create a custom 404 error page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# create a redirect location
echo -e \
"
http {
    include mime.types;
    # Show server host name as header
    add_header X-Served-By $hostname;

    server {
        listen 80;
        server_name localhost;

        root /var/www/html/;
        error_page 404 /404.html;

        location / {
            root /var/www/html/;
            index index.html index.nginx-debian.html;
        }

        location /redirect_me {
            return 301 https://www.youtube.com/watch?v=7VAI73roXaY;
        }

        location = /404.html {
            root /var/www/html;
            internal;
        }
    }
}

events {

}" | sudo tee /etc/nginx/nginx.conf

# Restarting nginx
sudo service nginx restart
