#!/usr/bin/env bash
# change your home IP

cp /etc/hosts hosts.new
sed -i s/"127.0.0.1	localhost"/"127.0.0.2	localhost"/ hosts.new
var="$(grep 'facebook.com' hosts.new)"
if [ ! -z "$var" ]
then
	sed -i s/"^.* facebook.com"/"8\.8\.8\.8 facebook\.com"/ hosts.new
else
	sed "$ a\8\.8\.8\.8 facebook.com" -i hosts.new
fi
cp -f hosts.new /etc/hosts
